<?php $this->headTitle()->prepend($page->getMetaTitle()); ?>
<?php $this->headMeta()->appendName('keywords', $page->getMetaKeywords()); ?>
<?php $this->headMeta()->appendName('description', $page->getMetaDescription()); ?>

<article>
    <?php if (!\Blog\Service\Page::isHomepage()): ?>
        <h1><?php echo $this->escapeHtml($page->getTitle()); ?></h1>
    <?php endif; ?>

    <?php echo $page->getContent(); ?>
</article>