<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Admin\Module'                    => __DIR__ . '/Module.php',
  'Admin\Controller\PageController' => __DIR__ . '/src/Admin/Controller/PageController.php',
  'Admin\Controller\BlogController' => __DIR__ . '/src/Admin/Controller/BlogController.php',
);
