<div class="header">
    <h1><?php echo $this->escapeHtml($blog->getTitle()); ?></h1>
    <h2><?php echo $this->escapeHtml($blog->getSubtitle()); ?></h2>
</div>

<?php echo $blog->getContent(); ?>

<footer>
    <div>
        <span class="date">
            Date added: <time datetime="<?php echo $blog->getDate() ?>"><?php echo $this->date($blog->getDate()) ?></time>
            <?php if($blog->getAuthor()): ?>
                by <span class="author"><a rel="author" href="/about.html"><?php echo $this->escapeHtml($blog->getAuthor()); ?></a></span>
            <?php endif; ?>
        </span>
    </div>
</footer>