<div class="header">
    <h1><?php echo $this->escapeHtml($blog->title); ?></h1>
    <h2><?php echo $this->escapeHtml($blog->subtitle); ?></h2>
</div>

<?php echo $blog->content; ?>


<footer>
    <span class="date">
        Date added: <time datetime="<?php echo $blog->date ?>"><?php echo $this->date($blog->date) ?></time>
        <?php if($blog->author): ?>
            ~ by <span class="author"><a rel="author" href="/about.html"><?php echo $this->escapeHtml($blog->author); ?></a></span>
        <?php endif; ?>
    </span>
</footer>