<?php $rating = ($blog->rating > 0  ? (int)$blog->rating : null); ?>

<div id="review" itemscope itemtype="http://data-vocabulary.org/Review">
    <hgroup>
        <h1><span itemprop="itemreviewed"><?php echo $this->escapeHtml($blog->title); ?></span></h1>
        <h2><?php echo $this->escapeHtml($blog->subtitle); ?></h2>
    </hgroup>

    <div itemprop="summary">
        <?php if ($blog->amazon_item_id): ?>
            <?php echo $this->amazon('ItemLookup', array('ItemId' => $blog->amazon_item_id, 'ResponseGroup' => 'Small,Images'), 'blogId-' . $blog->id); ?>
        <?php endif; ?>
        <p class="summary"><?php echo $blog->lead; ?></p>
    </div>

    <div itemprop="description">
        <?php echo $blog->content; ?>
    </div>
    
    <footer>
        <?php if (!empty($rating)): ?>
            <span class="rating">
                Rating: <span itemprop="rating"><?php echo $rating/2; ?></span> out of 5 stars
                <span class="stars star<?php echo $rating; ?>">
                    &nbsp;
                </span>
            </span>
        <?php endif; ?>
        <span class="reviewer">
            Reviewed by <span itemprop="reviewer"><?php echo ($blog->author ? $this->escapeHtml($blog->author) : 'Jaapsblog.nl') ?></span> on <time itemprop="dtreviewed" datetime="<?php echo $blog->date ?>"><?php echo $this->date($blog->date) ?></time>
        </span>
    </footer>
</div>