<?php echo $this->doctype(); ?>

<html lang="en">
    <head>

        <?php echo $this->headTitle(\Blog\Service\Page::websiteGlobals('title'))->setSeparator(' - '); ?>


        <?php echo $this->headMeta()->setCharset('UTF-8')
                                    ->setName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1'); ?>

        <?php echo $this->headLink(array(
            'rel'   => 'alternate',
            'type'  => 'application/rss+xml',
            'title' => 'RSS',
            'href'  => $this->basePath() . '/xml/rss.xml'
        ))->prependAlternate(array('rel' => 'shortcut icon', 'href'  => $this->basePath() . '/favicon.ico?v=' . \Blog\Service\Page::websiteGlobals('version')))
          ->prependStylesheet($this->basePath() . '/css/style.css?v=' . \Blog\Service\Page::websiteGlobals('version'))
          ->prependStylesheet($this->basePath() . '/css/main.css?v=' . \Blog\Service\Page::websiteGlobals('version'))
          ->prependStylesheet($this->basePath() . '/css/normalize.css?v=' . \Blog\Service\Page::websiteGlobals('version'))
          ->prependStylesheet('http://fonts.googleapis.com/css?family=Droid+Serif:400,600'); ?>


        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/main.js?v=' . \Blog\Service\Page::websiteGlobals('version'), 'text/javascript')
                                      ->prependFile($this->basePath() . '/js/vendor/modernizr-2.6.2.min.js')
                                      ->prependFile($this->basePath() . '/js/vendor/jquery-migrate-1.2.1.min.js')
                                      ->prependFile($this->basePath() . '/js/vendor/jquery-1.11.0.min.js'); ?>


        <?php echo $this->analytics(); ?>

    </head>
    
    <body>

        <nav>

            <?php echo $this->navigation('navigation')->menu()->setMaxDepth(0); ?>

        </nav>

        <div class="search">
            <form method="get" action="/blog">
                <input type="text" name="q" value="<?php echo $this->escapeHtml((isset($_GET['q']) ? $_GET['q'] : 'Search...')); ?>">
            </form>
        </div>

        <nav class="breadcrumbs">
            <div class="path">
<?php echo (!\Blog\Service\Page::isHomepage() ? '<a href="/">Home</a> > ' : ''); ?>
<?php echo (!\Blog\Service\Page::hasPage() ? 'Error' : ''); ?>
<?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setRenderInvisible(true); ?>
</div>
        </nav>

        <div class="page">
<!-- Content start -->
<?php echo trim($this->content); ?>

<!-- Content end -->
        </div>

        <?php echo $this->cookies(); ?>

        <?php echo $this->socialMedia(array('google' => array('plus'))); ?>

    </body>
</html>
