<?php echo $this->doctype(); ?>

<html lang="en">

    <head>

        <meta charset="utf-8">

        <?php echo $this->headTitle($this->siteTitle())->setSeparator(' - '); ?>

        <?php echo $this->headMeta()
                        ->prependName('viewport', 'width=device-width, initial-scale=1')
                        ->prependHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:300,700,100italic,400')
                        ->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet($this->basePath() . '/css/normalize.css') ?>

        <?php echo $this->headScript()
                        //->prependFile($this->basePath() . '/js/main.js')
                        ->prependFile($this->basePath() . '/js/vendor/modernizr-2.6.2.min.js'); ?>

    </head>

    <body>

        <div class="container">

            <div class="header">
                <div class="outer-container shadow-line">

                    <div class="inner-container clearfix">

                        <nav class="main">

                            <?php echo $this->navigation('Application/Navigation/Navigation')->menu()->setMaxDepth(0); ?>

                        </nav>

                        <div class="site-title">
                            <?php echo $this->escapeHtml($this->siteTitle()); ?> <i class="fa fa-code"></i>
                        </div>

                    </div>

                </div>

                <div class="outer-container">

                    <div class="inner-container">

                        <nav class="breadcrumbs">

                            <ul>
                                <li>You are here:</li>
                                <?php if ('home' === $this->navigation()->findActive('Application/Navigation/Navigation')['page']->getRoute()): ?>
                                    <li><a href="/">Home</a></li>
                                <?php else: ?>
                                    <li><a href="/">Home</a> &gt;</li>
                                    <li><?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setRenderInvisible(true); ?></li>
                                <?php endif; ?>
                            </ul>

                        </nav>

                    </div>

                </div>

            </div>

            <div class="outer-container body">

                <div class="inner-container clearfix">

                    <div class="column1">

                        <div class="content">

                            <?php echo $this->content; ?>

                        </div>

                    </div>

                    <div class="column2">

                        <?php echo $this->banners(); ?>

                    </div>


                </div>

            </div>

            <footer class="outer-container">

                <div class="inner-container">

                    <?php echo $this->footer(); ?>

                    <?php echo $this->socialNetworks(); ?>

                </div>

            </footer>

        </div>

    </body>

</html>
