<?php echo $this->doctype(); ?>

<html lang="en">

    <head>

        <meta charset="utf-8">
        <?php echo $this->headTitle('')->setSeparator(' - '); ?>

        <?php echo $this->headMeta()
                        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                        ->appendName('viewport', 'width=device-width, initial-scale=1') ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet($this->basePath() . '/css/normalize.css') ?>

        <?php echo $this->headScript()
                        ->prependFile($this->basePath() . '/js/main.js')
                        ->prependFile($this->basePath() . '/js/plugins.js')
                        ->prependFile($this->basePath() . '/js/vendor/jquery-1.10.2.min.js')
                        ->prependFile($this->basePath() . '/js/vendor/modernizr-2.6.2.min.js') ?>

    </head>

    <body>

        <?php echo $this->content; ?>

    </body>

</html>
