<?php $this->headTitle()->append($page->getMetaTitle()); ?>

<?php if(count($this->blogItems)): ?>
    <?php foreach($this->blogItems as $blogItem): ?>
        <a href="<?php echo $this->url('blog/item', array('item' => $blogItem->getSlug())); ?>">
            <article>
                <h1><?php echo $this->escapeHtml($blogItem->getTitle()); ?></h1>
                <h2><?php echo $this->escapeHtml($blogItem->getSubTitle()); ?></h2>
                <p><?php echo $this->escapeHtml($blogItem->getLead()); ?></p>

                <footer>
                    <?php $replies = count($blogItem->getReply()); ?>
                    <?php if ($replies > 0): ?>
                        <span><?php echo $replies . ($replies > 1 ? ' replies' : ' reply'); ?> <i class="fa fa-comments-o"></i></span>
                    <?php else: ?>
                        <span>No replies</span>
                    <?php endif; ?>
                </footer>

            </article>
        </a>
    <?php endforeach; ?>
<?php else: ?>
    <article>
        <h1><?php echo $this->escapeHtml($page->getTitle()); ?></h1>
        <p>No items found.</p>
    </article>
<?php endif; ?>
