<?php $this->headTitle()->prepend('Blog'); ?>
<?php $this->headMeta()->appendName('keywords', 'blog, items, jaapsblog, index'); ?>
<?php $this->headMeta()->appendName('description', 'Blog index.'); ?>

<div id="index">
<?php if ($q): ?>
    <p class="searched">Searched for: <span><?php echo $this->escapeHtml($q); ?></span></p>
<?php endif;?>
<?php if ($index->count() > 0): ?>
    <?php foreach($index as $key => $post): ?>
        <?php
            $href = $this->navigation('Navigation')->findOneBy('id_blog_post', $post->id)->getHref();
            $class = ('offline' == $post->status || strtotime($post->date) > time() ? ' class="hidden"' : null);
        ?>

        <article<?php echo $class;?>>

        	<div>
        		<h1>
        		    <a href="<?php echo $href; ?>" title="<?php echo $this->escapeHtml($post->title) ?>">
                        <?php echo $this->escapeHtml($post->title) ?>
                        <span class="category"><?php echo $this->escapeHtml($post->category); ?></span>
        		    </a>
        		</h1>
        		<h2><?php echo $this->escapeHtml($post->subtitle) ?></h2>
        	</div>
        	
        	<p><?php echo $post->lead ?></p>
        	
        	<a title="Read article: <?php echo $this->escapeHtml($post->title) ?>" href="<?php echo $href; ?>">Read more...</a>
        	
        	<footer>
        		Date added: <time datetime="<?php echo $post->date ?>"><?php echo $this->date($post->date) ?></time>
        	</footer>

        </article>
    <?php endforeach; ?>
<?php else: ?>
    <h1>Eh..?</h1>
    <p>What exactly are you lookin' for?</p>
<?php endif; ?>

</div>