<?php
    $this->headTitle()->prepend($page->getMetaTitle())->prepend($blog->getMetaTitle());
    $this->headMeta()->appendName('keywords', $blog->getMetaKeywords());
    $this->headMeta()->appendName('description', $blog->getMetaDescription());
?>

<article>
    <?php
        switch ($blog->getCategory()):
            default:
                require_once 'category/default.phtml';
        endswitch;
    ?>

    <?php echo $this->replies($blog->getId(), $blog->getTitle()); ?>
</article>

<div class="reply">
    <h6>Leave a comment</h6>
    <?php
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('csrf'));
    echo $this->formRow($form->get('name'));
    echo $this->formRow($form->get('comment'));
    //echo $this->formRow($form->get('captcha'));
    echo $this->formRow($form->get('submit'));
    ?>
    <?php echo $this->form()->closeTag(); ?>
</div>
