<?php
    $this->headTitle()->prepend($page->meta_title)->prepend($blog->meta_title);
    $this->headMeta()->appendName('keywords', $blog->meta_keywords);
    $this->headMeta()->appendName('description', $blog->meta_description);
?>

<article>
    <?php
        switch ($blog->category):
            default:
                require_once 'category/default.phtml';
        endswitch;
    ?>

    <?php echo $this->replies($blog->id, $blog->title); ?>
</article>

<div class="reply">
    <h6>Leave a comment</h6>
    <?php
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('csrf'));
    echo $this->formRow($form->get('name'));
    echo $this->formRow($form->get('comment'));
    //echo $this->formRow($form->get('captcha'));
    echo $this->formRow($form->get('submit'));
    ?>
    <?php echo $this->form()->closeTag(); ?>
</div>
